<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>np_info_expirationdate</name>
   <tag></tag>
   <elementGuidId>7363dfe9-2104-41d4-a435-bb021d6e699d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#expiration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#expiration</value>
   </webElementProperties>
</WebElementEntity>
