<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>oasis_soc_print_view</name>
   <tag></tag>
   <elementGuidId>0752266e-7f85-4c26-a0d5-1d7a89d2e1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#switchview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#switchview</value>
   </webElementProperties>
</WebElementEntity>
