<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>oasis_soc_time_out</name>
   <tag></tag>
   <elementGuidId>6bae350e-e43c-464b-857b-eb894e9d6754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#to</value>
   </webElementProperties>
</WebElementEntity>
