<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>oasis_soc_visit_date</name>
   <tag></tag>
   <elementGuidId>9377ccd4-10b9-4792-b85e-e34d1a694b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitDate</value>
   </webElementProperties>
</WebElementEntity>
