<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adls_GG0100_priorfunctioning_a</name>
   <tag></tag>
   <elementGuidId>b21e9cf4-6577-4e27-9d8a-892adbd81b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GG0100A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GG0100A</value>
   </webElementProperties>
</WebElementEntity>
