<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adls_GG0100_priorfunctioning_d</name>
   <tag></tag>
   <elementGuidId>b5296aaa-e065-4189-bdd5-c14807703d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GG0100D</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GG0100D</value>
   </webElementProperties>
</WebElementEntity>
