<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adls_GG0100_priorfunctioning_c</name>
   <tag></tag>
   <elementGuidId>abccbb02-a9b5-4943-926b-0014f7f356c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GG0100C</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GG0100C</value>
   </webElementProperties>
</WebElementEntity>
