<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adls_GG0100_priorfunctioning_b</name>
   <tag></tag>
   <elementGuidId>a7a4f3b9-ea43-4ad6-87f0-923a69f93766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GG0100B</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GG0100B</value>
   </webElementProperties>
</WebElementEntity>
