<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tm_taskdate</name>
   <tag></tag>
   <elementGuidId>aec13926-e0df-480f-8177-807798b0149d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#selecteddate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#selecteddate</value>
   </webElementProperties>
</WebElementEntity>
