<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>29ad60ea-987f-44f2-a7d4-3b49438ae33f</testSuiteGuid>
   <testCaseLink>
      <guid>4c2ee830-fb68-4005-9409-23b0f046370d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6f10e20b-1af4-41f5-bbbe-64fa30a74247</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login2</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6f10e20b-1af4-41f5-bbbe-64fa30a74247</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>7d2b587d-7119-4dfd-96ee-eba5a9d40f0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6f10e20b-1af4-41f5-bbbe-64fa30a74247</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>ed3bd448-9a8b-4f34-b5b7-3d78a3e23440</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
