<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>whole_calendar</name>
   <tag></tag>
   <elementGuidId>27784df5-7c0e-47b6-90be-161c106310ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#datepicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#datepicker</value>
   </webElementProperties>
</WebElementEntity>
