<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_info_fname</name>
   <tag></tag>
   <elementGuidId>954e6d9b-95a4-4f61-b2b3-bb782010e642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#first_name</value>
   </webElementProperties>
</WebElementEntity>
