<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_info_suffix</name>
   <tag></tag>
   <elementGuidId>ed2f9097-c2b4-40cf-bcef-976dfd6822b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#suffix</value>
   </webElementProperties>
</WebElementEntity>
