<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_info_minitial</name>
   <tag></tag>
   <elementGuidId>1fe87264-0083-4a17-9bb7-c2f75f781ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#mi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#mi</value>
   </webElementProperties>
</WebElementEntity>
