<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_info_lname</name>
   <tag></tag>
   <elementGuidId>9935ff5a-6a57-486c-b533-0ed9879eab7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#last_name</value>
   </webElementProperties>
</WebElementEntity>
