<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_info_bdate</name>
   <tag></tag>
   <elementGuidId>ea814dec-4021-4a3d-b1e7-aa44b7f3a172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#birthdate</value>
   </webElementProperties>
</WebElementEntity>
