<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>30ds_date</name>
   <tag></tag>
   <elementGuidId>bca8d420-1bc5-449d-a28b-bd73a7108cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#date</value>
   </webElementProperties>
</WebElementEntity>
