<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>livingsituation_caregivername</name>
   <tag></tag>
   <elementGuidId>83272f35-7ec6-4949-944a-3594b25f86a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ls_caregiver</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ls_caregiver</value>
   </webElementProperties>
</WebElementEntity>
