<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addproductsorservices_title</name>
   <tag></tag>
   <elementGuidId>343bf641-a030-43f9-8324-3c178f63db7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#title</value>
   </webElementProperties>
</WebElementEntity>
