<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addvendortype_title</name>
   <tag></tag>
   <elementGuidId>b0bc2a34-ce45-4fd8-a2d9-2d04e2103b6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#title</value>
   </webElementProperties>
</WebElementEntity>
