<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nhv_zipcode</name>
   <tag></tag>
   <elementGuidId>bd1e5724-ce23-4434-a68d-c106cf1f4e17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#zipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#zipCode</value>
   </webElementProperties>
</WebElementEntity>
