<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>poc_receiveddate</name>
   <tag></tag>
   <elementGuidId>24fd7957-5a71-424a-af35-7cbac15873d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#receiveDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#receiveDate</value>
   </webElementProperties>
</WebElementEntity>
