<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ccnote_date</name>
   <tag></tag>
   <elementGuidId>9d8a8f2c-edaf-4dc2-8a1e-fac23282cfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#date</value>
   </webElementProperties>
</WebElementEntity>
