<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeLivingSituationCaregiverName</name>
   <tag></tag>
   <elementGuidId>21aabf09-1ef6-4e1c-b0a2-22473254b1c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ls_caregiver</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ls_caregiver</value>
   </webElementProperties>
</WebElementEntity>
