<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeHospitalizationInfoFacilityDCdate</name>
   <tag></tag>
   <elementGuidId>5433fcae-8aea-4cfa-a6ed-9af5a13e95df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#discharge_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#discharge_date</value>
   </webElementProperties>
</WebElementEntity>
