<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeAddStreet</name>
   <tag></tag>
   <elementGuidId>f25ce979-b137-4c87-9ff6-47aba6c87fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_street</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_street</value>
   </webElementProperties>
</WebElementEntity>
