<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IntakeInsuranceInfoPrimaryNumber</name>
   <tag></tag>
   <elementGuidId>5e9a379a-2fca-44c1-869a-424255f96656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#primary_insurance_policy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#primary_insurance_policy</value>
   </webElementProperties>
</WebElementEntity>
