<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeHospitalizationInfoFacilityAdmitDate</name>
   <tag></tag>
   <elementGuidId>ed5e1b16-7955-4a5c-9c9c-bed973e47a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#admit_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#admit_date</value>
   </webElementProperties>
</WebElementEntity>
