<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeDiagandPreAdPrimary</name>
   <tag></tag>
   <elementGuidId>40702db2-b419-4f9c-afc5-32e3c4c74dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#primary_diagnosis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#primary_diagnosis</value>
   </webElementProperties>
</WebElementEntity>
