<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeAddZip</name>
   <tag></tag>
   <elementGuidId>0363e825-8962-47c7-af40-177f08e991d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_zipcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_zipcode</value>
   </webElementProperties>
</WebElementEntity>
