<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakePhysicianInfoAttending</name>
   <tag></tag>
   <elementGuidId>22870206-7905-4295-b733-861231aeab51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physician_attending_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physician_attending_chosen</value>
   </webElementProperties>
</WebElementEntity>
