<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeSSN</name>
   <tag></tag>
   <elementGuidId>03655618-5cd6-475a-8909-20c3e572c3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ssNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ssNumber</value>
   </webElementProperties>
</WebElementEntity>
