<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeEmergencyName</name>
   <tag></tag>
   <elementGuidId>e5546b62-2a99-4a16-b4bb-c41efbab97d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ec_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ec_name</value>
   </webElementProperties>
</WebElementEntity>
