<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeAddress2</name>
   <tag></tag>
   <elementGuidId>a035c8cf-f950-4465-a5e5-5ee13de4c7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_line2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_line2</value>
   </webElementProperties>
</WebElementEntity>
