<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeReferralInfoTypeOfReferral</name>
   <tag></tag>
   <elementGuidId>72e53ee4-6382-47b3-bfdf-20c0a22072ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#referral_type_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#referral_type_chosen</value>
   </webElementProperties>
</WebElementEntity>
