<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakePhysicianInfoPrimary</name>
   <tag></tag>
   <elementGuidId>1ec6c76e-e307-42d3-abfd-4b09d28fda96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physician_primary_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physician_primary_chosen</value>
   </webElementProperties>
</WebElementEntity>
