<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeAddEmail</name>
   <tag></tag>
   <elementGuidId>39e20d6c-c7c1-4f43-b414-66aae9ce4b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_email</value>
   </webElementProperties>
</WebElementEntity>
