<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeAddCity</name>
   <tag></tag>
   <elementGuidId>b20807ce-68ec-4b3b-8dfb-eafe91b5cc5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_city</value>
   </webElementProperties>
</WebElementEntity>
