<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeEmergencyPhone2</name>
   <tag></tag>
   <elementGuidId>27ee4d6a-9459-4d1a-8356-cc4f6e44c43d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ec_other_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ec_other_phone</value>
   </webElementProperties>
</WebElementEntity>
