<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeDiagandPreAdSurgery</name>
   <tag></tag>
   <elementGuidId>4ff287ad-4002-4d7d-8754-aa87b890dfe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#diagnosis_surgery</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#diagnosis_surgery</value>
   </webElementProperties>
</WebElementEntity>
