<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeReferralInfoReferralSource</name>
   <tag></tag>
   <elementGuidId>258cb7b0-c55f-4ef0-bdc2-46c9abc2aaa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#referral_source_id_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#referral_source_id_chosen</value>
   </webElementProperties>
</WebElementEntity>
