<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeEthnicity</name>
   <tag></tag>
   <elementGuidId>17bfc001-6aeb-4ab2-8a27-658374442933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ethnicities_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ethnicities_chosen</value>
   </webElementProperties>
</WebElementEntity>
