<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeDiagandPreAdIV</name>
   <tag></tag>
   <elementGuidId>617c2589-a07d-4aaf-9ab6-f69e3fc66ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#iv_theraphy_order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#iv_theraphy_order</value>
   </webElementProperties>
</WebElementEntity>
