<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intakeDropdown</name>
   <tag></tag>
   <elementGuidId>0da089af-c43e-4a35-a41e-990110b6cb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ethnicities_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ethnicities_chosen</value>
   </webElementProperties>
</WebElementEntity>
