<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signs_abuse_actual</name>
   <tag></tag>
   <elementGuidId>49ac1c6a-818d-4f32-91fc-2e998332c3f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[20]/td[2]/table/tbody/tr[2]/td/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#neuroForm > div > fieldset > table > tbody > tr:nth-child(20) > td.oasis__answer > table > tbody > tr:nth-child(2) > td > div > label > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;neuroForm&quot;]/div/fieldset/table/tbody/tr[20]/td[2]/table/tbody/tr[2]/td/div/label/input</value>
   </webElementProperties>
</WebElementEntity>
