<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ao_ordertime</name>
   <tag></tag>
   <elementGuidId>0e1b6822-9c8b-4c89-a7ab-7b7b9e26ac6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderTime</value>
   </webElementProperties>
</WebElementEntity>
