<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ao_orderdate</name>
   <tag></tag>
   <elementGuidId>6618ff4d-579b-4d2a-ab73-abfbc580984f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderDate</value>
   </webElementProperties>
</WebElementEntity>
