<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ao_sentdate</name>
   <tag></tag>
   <elementGuidId>3f700b34-2197-4946-9ef8-f09e8fb826a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sentDate</value>
   </webElementProperties>
</WebElementEntity>
