<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endo_dfex_footexamfreq_other</name>
   <tag></tag>
   <elementGuidId>195e41f8-260b-4e93-ae18-9d3b80ef7f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOENDO0019</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOENDO0019</value>
   </webElementProperties>
</WebElementEntity>
