<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>po_commnote</name>
   <tag></tag>
   <elementGuidId>018db820-2f7f-44ce-8fb6-f18afda98fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#communicationnote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#communicationnote</value>
   </webElementProperties>
</WebElementEntity>
