<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>po_orderdate</name>
   <tag></tag>
   <elementGuidId>6937918c-a0c0-4276-8473-f6c9188efbc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderdate</value>
   </webElementProperties>
</WebElementEntity>
