<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>po_ordertime</name>
   <tag></tag>
   <elementGuidId>8b4d15b7-4d6b-48a6-8086-8d9276a6fe75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderTime</value>
   </webElementProperties>
</WebElementEntity>
