<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>po_porder</name>
   <tag></tag>
   <elementGuidId>e8595795-c037-41b5-b9b9-4403f8ebe00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physicianordernotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physicianordernotes</value>
   </webElementProperties>
</WebElementEntity>
