<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>po_sendate</name>
   <tag></tag>
   <elementGuidId>b220a2b5-1d9b-445a-8d99-f32aaf890f31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sentDate</value>
   </webElementProperties>
</WebElementEntity>
