<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endo_diabetes_bloodglucosetesting_other</name>
   <tag></tag>
   <elementGuidId>b4211404-d22d-493b-a34d-1b7f38db35ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOENDO0016</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOENDO0016</value>
   </webElementProperties>
</WebElementEntity>
