<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endo_diabetes_cgmbrand_tf</name>
   <tag></tag>
   <elementGuidId>efb678bf-2f1e-460e-81da-16aca8e9dd75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOENDO0101</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOENDO0101</value>
   </webElementProperties>
</WebElementEntity>
