<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cardio_rs_tracheo_datelastchange</name>
   <tag></tag>
   <elementGuidId>4444b9b2-ef34-498a-b4e9-ec53321383f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOCARDIO0089</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOCARDIO0089</value>
   </webElementProperties>
</WebElementEntity>
