<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birthdate_field</name>
   <tag></tag>
   <elementGuidId>3d0fce86-f126-44a9-a0c1-6ca9ab4e2857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#birthdate</value>
   </webElementProperties>
</WebElementEntity>
