<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>car_insurance_effectivedate</name>
   <tag></tag>
   <elementGuidId>e3783ecf-a25d-4e78-b848-bb5ab3fd7ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdate4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdate4</value>
   </webElementProperties>
</WebElementEntity>
