<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chest_xray_effectivedate</name>
   <tag></tag>
   <elementGuidId>3417ca28-7748-4a74-9c55-e60a84563b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpefdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpefdate2</value>
   </webElementProperties>
</WebElementEntity>
