<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chest_xray_expirationdate</name>
   <tag></tag>
   <elementGuidId>3f9db259-2986-435b-9fc5-5075c677e4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpexpdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpexpdate2</value>
   </webElementProperties>
</WebElementEntity>
