<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chest_xray_dateverified</name>
   <tag></tag>
   <elementGuidId>63b70b26-c1bd-46f5-b1b6-6f7c4ba8d503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpdatev2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpdatev2</value>
   </webElementProperties>
</WebElementEntity>
