<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cpr_bls_effectivedate</name>
   <tag></tag>
   <elementGuidId>5dbfff80-ca5d-4547-a289-03703281c52d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdate2</value>
   </webElementProperties>
</WebElementEntity>
