<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cpr_bls_expirationdate</name>
   <tag></tag>
   <elementGuidId>752956fe-3b01-4bdc-9a3d-8cba1fd43a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#exdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#exdate2</value>
   </webElementProperties>
</WebElementEntity>
