<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cpr_bls_dateverified</name>
   <tag></tag>
   <elementGuidId>7b7b9956-7e6a-435b-8843-d76eb27309ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#verdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#verdate2</value>
   </webElementProperties>
</WebElementEntity>
