<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>driver_license_effectivedate</name>
   <tag></tag>
   <elementGuidId>9e6a68fe-8620-4451-8018-b20b8f292b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdate3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdate3</value>
   </webElementProperties>
</WebElementEntity>
