<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>driver_license_expirationdate</name>
   <tag></tag>
   <elementGuidId>2c6ae51f-0a29-44c8-a635-fa57631f89ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#exdate3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#exdate3</value>
   </webElementProperties>
</WebElementEntity>
