<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hired_Date</name>
   <tag></tag>
   <elementGuidId>855ed161-70b9-4e54-bf84-e20ca957262c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hireddate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hireddate</value>
   </webElementProperties>
</WebElementEntity>
