<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthdate</name>
   <tag></tag>
   <elementGuidId>41592e77-ee92-429b-ac1c-ce7b60043e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#birthdate</value>
   </webElementProperties>
</WebElementEntity>
