<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>license_certificate_expirationdate</name>
   <tag></tag>
   <elementGuidId>14a0a1b5-affa-4ac5-994b-15fc229f7050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#exdate1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#exdate1</value>
   </webElementProperties>
</WebElementEntity>
