<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>license_certificate_effectivedate</name>
   <tag></tag>
   <elementGuidId>9b363e03-e14f-41b9-a271-d21559f2ab28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdate1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdate1</value>
   </webElementProperties>
</WebElementEntity>
