<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>physical_examination_dateverified</name>
   <tag></tag>
   <elementGuidId>7eb3d511-dce7-4cfc-ac07-2858150f06eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpdatev0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpdatev0</value>
   </webElementProperties>
</WebElementEntity>
