<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>physical_examination_expirationdate</name>
   <tag></tag>
   <elementGuidId>0e7a5a56-9860-4c5f-8f95-febd37471f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpexpdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpexpdate0</value>
   </webElementProperties>
</WebElementEntity>
