<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>physical_examination_effectivedate</name>
   <tag></tag>
   <elementGuidId>07af532e-7a98-49d3-a631-c707405a006f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpefdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpefdate0</value>
   </webElementProperties>
</WebElementEntity>
