<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>professional_license_effectivedate</name>
   <tag></tag>
   <elementGuidId>8b3e2252-5704-473f-b397-4e3e7b8e5433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdate0</value>
   </webElementProperties>
</WebElementEntity>
