<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termination_Date</name>
   <tag></tag>
   <elementGuidId>6a41e326-d9f5-4eab-84f2-9db3a2040647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#terminationdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#terminationdate</value>
   </webElementProperties>
</WebElementEntity>
