<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termination_date_field</name>
   <tag></tag>
   <elementGuidId>fc427fda-5de3-4934-a1a5-cad8abceaba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#terminationdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#terminationdate</value>
   </webElementProperties>
</WebElementEntity>
