<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_bdate</name>
   <tag></tag>
   <elementGuidId>82bc2d4b-6bfa-46e5-a545-64ef91bc2c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#birthdate</value>
   </webElementProperties>
</WebElementEntity>
