<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endo_dfex_gm_datelasttestingdone</name>
   <tag></tag>
   <elementGuidId>a29e7fba-9203-4945-8f3d-d0aeffecf264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOENDO0078</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOENDO0078</value>
   </webElementProperties>
</WebElementEntity>
