<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SOC_M0016</name>
   <tag></tag>
   <elementGuidId>e37bc84c-3194-449e-8221-c6fe752f4576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M0016</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M0016</value>
   </webElementProperties>
</WebElementEntity>
