<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pcffe_datef2fencounter</name>
   <tag></tag>
   <elementGuidId>cfbe5925-9c8c-42fe-b3ee-4cd6ef9b90fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderDate</value>
   </webElementProperties>
</WebElementEntity>
