<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1800_1</name>
   <tag></tag>
   <elementGuidId>1d3b0221-e7f0-4192-9fbf-f2e2de68fb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[9]/td[2]/table/tbody/tr/td/div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#adlForm > div > fieldset > table > tbody > tr:nth-child(9) > td.oasis__answer > table > tbody > tr > td > div:nth-child(2) > label > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[9]/td[2]/table/tbody/tr/td/div[2]/label/input</value>
   </webElementProperties>
</WebElementEntity>
