<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1810_0</name>
   <tag></tag>
   <elementGuidId>c4cce141-bea1-438e-b2a9-164faa770265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr/td/div[1]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#adlForm > div > fieldset > table > tbody > tr:nth-child(11) > td.oasis__answer > table > tbody > tr > td > div:nth-child(1) > label > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[11]/td[2]/table/tbody/tr/td/div[1]/label/input</value>
   </webElementProperties>
</WebElementEntity>
