<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dodah_ordertime</name>
   <tag></tag>
   <elementGuidId>3184da7b-cd88-4a8d-9ad2-38ce319ba5d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderTime</value>
   </webElementProperties>
</WebElementEntity>
