<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dodah_sentdate</name>
   <tag></tag>
   <elementGuidId>da1bb192-cda8-4630-9fc1-778ac016f988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sentDate</value>
   </webElementProperties>
</WebElementEntity>
