<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dodah_orderdate</name>
   <tag></tag>
   <elementGuidId>9cae439e-4cee-43cb-9079-d77a760e3edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderDate</value>
   </webElementProperties>
</WebElementEntity>
