<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password</name>
   <tag></tag>
   <elementGuidId>c837136b-bf97-4898-9ba6-d08808b1106d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#loginpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#loginpassword</value>
   </webElementProperties>
</WebElementEntity>
