<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>70ab3bb6-a926-4a02-bfb1-b83c5c907073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#loginemail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#loginemail</value>
   </webElementProperties>
</WebElementEntity>
