<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transfer_order_date</name>
   <tag></tag>
   <elementGuidId>984f13d4-a4b0-4b00-b610-7e745fdcd070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderDate</value>
   </webElementProperties>
</WebElementEntity>
