<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transfer_order_PO</name>
   <tag></tag>
   <elementGuidId>45148915-c374-4ccb-841d-9b38c73f1357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physicianordernotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physicianordernotes</value>
   </webElementProperties>
</WebElementEntity>
