<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>trasnfer_order_comm</name>
   <tag></tag>
   <elementGuidId>b021e517-3885-4dca-af14-f62165f98c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#communicationnotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#communicationnotes</value>
   </webElementProperties>
</WebElementEntity>
