<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>casecon_followupdate</name>
   <tag></tag>
   <elementGuidId>5119660c-fcab-4001-b327-41bd15163841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#dp1559800867535</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#dp1559800867535</value>
   </webElementProperties>
</WebElementEntity>
