<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rec_sentdate</name>
   <tag></tag>
   <elementGuidId>d2b785da-2f78-4517-8eb5-a7b681c36024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sentDate</value>
   </webElementProperties>
</WebElementEntity>
