<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rec_receiveddate</name>
   <tag></tag>
   <elementGuidId>6b5b57ce-1f54-4697-9b95-fcd2ea5918b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#receiveDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#receiveDate</value>
   </webElementProperties>
</WebElementEntity>
