<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elim_hemodialysis_avshunt_ra</name>
   <tag></tag>
   <elementGuidId>a75fb19d-1cef-4f2b-bb5d-b5fd57df25c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOELIMINATION0030</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOELIMINATION0030</value>
   </webElementProperties>
</WebElementEntity>
