<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elim_hemodialysis_thrill_yes</name>
   <tag></tag>
   <elementGuidId>6f56aa28-3694-4214-b941-93b7a475ce56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SOOELIMINATION0033</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SOOELIMINATION0033</value>
   </webElementProperties>
</WebElementEntity>
