<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snv_time-in</name>
   <tag></tag>
   <elementGuidId>42033f29-1f26-4002-a6ff-7c9afe1fc77a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#timeIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#timeIn</value>
   </webElementProperties>
</WebElementEntity>
