<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snv_visit_date</name>
   <tag></tag>
   <elementGuidId>697f11bc-3729-4dba-8e98-268b6e5634e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitDate</value>
   </webElementProperties>
</WebElementEntity>
