<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snv_time_out</name>
   <tag></tag>
   <elementGuidId>289a5a80-2352-46b0-97c3-dcccbb5ad6b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#timeOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#timeOut</value>
   </webElementProperties>
</WebElementEntity>
