<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis</name>
   <tag></tag>
   <elementGuidId>7d2a2da7-a3f5-4822-9f1d-d65f979406c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#diagnosis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#diagnosis</value>
   </webElementProperties>
</WebElementEntity>
