<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmotionalStatus_inputbox</name>
   <tag></tag>
   <elementGuidId>5c29e93f-b8e0-40c1-b1eb-58c288d39a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#emoStatTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#emoStatTxt</value>
   </webElementProperties>
</WebElementEntity>
