<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Other_Diagosis</name>
   <tag></tag>
   <elementGuidId>aa004b8a-4341-47bd-acab-0efafd1693e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#diagnosisOther</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#diagnosisOther</value>
   </webElementProperties>
</WebElementEntity>
