<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time_In</name>
   <tag></tag>
   <elementGuidId>4bed894b-9c97-4b51-b037-8b2e5ae16b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#timeIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#timeIn</value>
   </webElementProperties>
</WebElementEntity>
