<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time_Out</name>
   <tag></tag>
   <elementGuidId>483ddbbd-9da9-4758-b216-a98d368fca00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#timeOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#timeOut</value>
   </webElementProperties>
</WebElementEntity>
