<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VisitGoals_Otherinput</name>
   <tag></tag>
   <elementGuidId>d031d812-6722-4a9e-b2bd-d1847902bc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitGoalsTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitGoalsTxt</value>
   </webElementProperties>
</WebElementEntity>
