<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Visit_Date</name>
   <tag></tag>
   <elementGuidId>1f518c78-2c1c-4d0a-afd5-88103a3a3e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitDate</value>
   </webElementProperties>
</WebElementEntity>
