<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VisitInter_inputbox</name>
   <tag></tag>
   <elementGuidId>efd1bc06-8175-4d2e-9cbc-0a1acbda8da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#visitInterventionsTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#visitInterventionsTxt</value>
   </webElementProperties>
</WebElementEntity>
