<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcsum_dcnotifdate_patientfamily</name>
   <tag></tag>
   <elementGuidId>ef774ead-d0ef-4a5e-b21a-cdd99ade0495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#patFamCare</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#patFamCare</value>
   </webElementProperties>
</WebElementEntity>
