<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_address_email</name>
   <tag></tag>
   <elementGuidId>a38b4b3f-2187-45af-a1cf-0aa709a2ab5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_email</value>
   </webElementProperties>
</WebElementEntity>
