<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_address_address1</name>
   <tag></tag>
   <elementGuidId>b165c95d-f304-44b3-91fe-cab60a6953b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_line1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_line1</value>
   </webElementProperties>
</WebElementEntity>
