<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_address_city</name>
   <tag></tag>
   <elementGuidId>4520282e-cb3d-4f0d-82fc-e4b885ca3185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_city</value>
   </webElementProperties>
</WebElementEntity>
