<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_address_address2</name>
   <tag></tag>
   <elementGuidId>83517cfb-761d-4153-9f2e-45be135a9b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_line2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_line2</value>
   </webElementProperties>
</WebElementEntity>
