<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_address_majorcrossstr</name>
   <tag></tag>
   <elementGuidId>9184af96-628f-4dbe-9c49-4688d4043b09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_street</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_street</value>
   </webElementProperties>
</WebElementEntity>
