<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_adddress_ZIPcode</name>
   <tag></tag>
   <elementGuidId>d5d16c9b-9b9c-4fd8-92d2-3c7655d2b2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#main_zipcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#main_zipcode</value>
   </webElementProperties>
</WebElementEntity>
