<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diagnosis_primary</name>
   <tag></tag>
   <elementGuidId>7abe5087-b078-4dc8-aa49-86d5f9e99cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#primary_diagnosis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#primary_diagnosis</value>
   </webElementProperties>
</WebElementEntity>
