<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diagnosis_surgery</name>
   <tag></tag>
   <elementGuidId>1a5654e8-bbb2-49c8-9cb3-8c465109e216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#diagnosis_surgery</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#diagnosis_surgery</value>
   </webElementProperties>
</WebElementEntity>
