<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diagnosis_pre-ad_orders</name>
   <tag></tag>
   <elementGuidId>e316ed3f-b07f-4c89-a412-55fcb397c395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#diagnosis_adm_order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#diagnosis_adm_order</value>
   </webElementProperties>
</WebElementEntity>
