<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pre-ad_ref_date</name>
   <tag></tag>
   <elementGuidId>e14be397-740f-45d8-852e-ed3ab8617a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#refDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#refDate</value>
   </webElementProperties>
</WebElementEntity>
