<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcins_dcdate</name>
   <tag></tag>
   <elementGuidId>cf5af739-ba46-4127-a0fd-ae513eea2146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#dischargeDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#dischargeDate</value>
   </webElementProperties>
</WebElementEntity>
