<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcins_wearepleasedtoprovideservicetoyou_time</name>
   <tag></tag>
   <elementGuidId>37f67967-7c85-4b59-bfea-51adc419b087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#time</value>
   </webElementProperties>
</WebElementEntity>
