<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcins_wearepleasedtoprovideservicetoyou_date</name>
   <tag></tag>
   <elementGuidId>b8d9eb57-a8f1-4126-aaf7-76c19a5813d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#appointmentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#appointmentDate</value>
   </webElementProperties>
</WebElementEntity>
