<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cc_additonalassessments</name>
   <tag></tag>
   <elementGuidId>d0f31fa0-a9cc-403c-ae7f-a4c60a515a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#DMEREQ0119</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#DMEREQ0119</value>
   </webElementProperties>
</WebElementEntity>
