<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cc_regarding</name>
   <tag></tag>
   <elementGuidId>0fca71b8-9d5a-4bc8-83eb-09f94e0eb882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#DMEREQ0102</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#DMEREQ0102</value>
   </webElementProperties>
</WebElementEntity>
