<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uo_nephrostomy</name>
   <tag></tag>
   <elementGuidId>0da6674e-3fa5-4f92-abcc-a84103a39a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GENSTAS0020</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GENSTAS0020</value>
   </webElementProperties>
</WebElementEntity>
