<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pd_type_capd</name>
   <tag></tag>
   <elementGuidId>e689429f-93e9-49cb-b585-36cdbe93c54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#PERDIA0006</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#PERDIA0006</value>
   </webElementProperties>
</WebElementEntity>
