<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>admitClickSOC_timeIn</name>
   <tag></tag>
   <elementGuidId>27b439e6-092a-490b-95b0-a3b23c0dd645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ti</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ti</value>
   </webElementProperties>
</WebElementEntity>
