<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tracheostomy_datelastchange</name>
   <tag></tag>
   <elementGuidId>047033ee-ade4-4719-84bb-731e10641742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#RESP0049</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#RESP0049</value>
   </webElementProperties>
</WebElementEntity>
