<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emergency_name</name>
   <tag></tag>
   <elementGuidId>813ac5d1-57ed-416f-a347-37d2d9b66501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ec_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ec_name</value>
   </webElementProperties>
</WebElementEntity>
