<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emergency_phone1</name>
   <tag></tag>
   <elementGuidId>bd305a55-5cda-4741-8c8e-60ab3ab70197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ec_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ec_phone</value>
   </webElementProperties>
</WebElementEntity>
