<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emergency_phone2</name>
   <tag></tag>
   <elementGuidId>ae5d2829-a037-458f-b196-e54790913e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ec_other_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ec_other_phone</value>
   </webElementProperties>
</WebElementEntity>
