<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pva_dateinserted</name>
   <tag></tag>
   <elementGuidId>eb97a0dd-35df-4899-b1fc-630e5cc96df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#VAAIT0005</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#VAAIT0005</value>
   </webElementProperties>
</WebElementEntity>
