<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_emwf_startson</name>
   <tag></tag>
   <elementGuidId>822ddd2c-acfe-45eb-a8d6-4da920673b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#mwfstartson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#mwfstartson</value>
   </webElementProperties>
</WebElementEntity>
