<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_emwf_endson</name>
   <tag></tag>
   <elementGuidId>e30e61e6-b2eb-4bdb-a5c5-611e4fc0aab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#mwfendson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#mwfendson</value>
   </webElementProperties>
</WebElementEntity>
