<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xitemedits_btn</name>
   <tag></tag>
   <elementGuidId>67fec96c-b1e5-4d52-93eb-71ccb3574e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#closecomments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#closecomments</value>
   </webElementProperties>
</WebElementEntity>
