<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_daily_endson</name>
   <tag></tag>
   <elementGuidId>a09fa69c-9a3c-4e1b-8ae2-dc9449d190e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#dailyendson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#dailyendson</value>
   </webElementProperties>
</WebElementEntity>
