<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1311_D1</name>
   <tag></tag>
   <elementGuidId>ea3331bb-3188-4528-9755-35b63e44de46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1311_NSTG_DRSG_D1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1311_NSTG_DRSG_D1</value>
   </webElementProperties>
</WebElementEntity>
