<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1311_B1</name>
   <tag></tag>
   <elementGuidId>f91024f9-018c-4f96-b6ef-ff7bc0058cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1311_NBR_PRSULC_STG3_B1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1311_NBR_PRSULC_STG3_B1</value>
   </webElementProperties>
</WebElementEntity>
