<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1311_E1</name>
   <tag></tag>
   <elementGuidId>1e31b148-47ce-4c57-ad63-84ce8ddeaef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1311_NSTG_CVRG_E1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1311_NSTG_CVRG_E1</value>
   </webElementProperties>
</WebElementEntity>
