<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1311_C1</name>
   <tag></tag>
   <elementGuidId>46c63c40-e16c-4123-b7d3-2b59b433ef33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1311_NBR_PRSULC_STG4_C1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1311_NBR_PRSULC_STG4_C1</value>
   </webElementProperties>
</WebElementEntity>
