<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>woundinfo_drawlength</name>
   <tag></tag>
   <elementGuidId>f725470f-754c-458f-be1f-acba424d264a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#canvas</value>
   </webElementProperties>
</WebElementEntity>
