<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M2102_2</name>
   <tag></tag>
   <elementGuidId>b50b1a88-cbb6-4445-822b-d04564106d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M2102_CARE_TYPE_SRC_SPRVSN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M2102_CARE_TYPE_SRC_SPRVSN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;M2102_CARE_TYPE_SRC_SPRVSN&quot;]</value>
   </webElementProperties>
</WebElementEntity>
