<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iuc_datelastchanged</name>
   <tag></tag>
   <elementGuidId>4b077f8c-9f9d-4441-8c2c-74417d0269e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GENSTAS0028</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GENSTAS0028</value>
   </webElementProperties>
</WebElementEntity>
