<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iuc_cathtype_urethral</name>
   <tag></tag>
   <elementGuidId>471ff79b-6b97-445a-bf37-47177d8d7ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GENSTAS0009</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GENSTAS0009</value>
   </webElementProperties>
</WebElementEntity>
