<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_licensecertverification_effectivedate</name>
   <tag></tag>
   <elementGuidId>0ae0b690-138e-4d2c-a343-2e26ba4e7d79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdateu1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdateu1</value>
   </webElementProperties>
</WebElementEntity>
