<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_cprbls_effectivedate</name>
   <tag></tag>
   <elementGuidId>0176f00b-cd62-4a68-b17f-45f5ab6b449f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdateu2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdateu2</value>
   </webElementProperties>
</WebElementEntity>
