<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_driverlicense_effectivedate</name>
   <tag></tag>
   <elementGuidId>876f3574-0ddb-4c80-8ee4-c7fada361443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdateu3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdateu3</value>
   </webElementProperties>
</WebElementEntity>
