<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_driverlicense_dateverified</name>
   <tag></tag>
   <elementGuidId>f2938339-cf2a-4d4f-961a-2b7ac0a697e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#verdate3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#verdate3</value>
   </webElementProperties>
</WebElementEntity>
