<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_carinsurance_expirationdate</name>
   <tag></tag>
   <elementGuidId>e4c422a7-7171-44d5-8898-fd155afec544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#exdate4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#exdate4</value>
   </webElementProperties>
</WebElementEntity>
