<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_licensecertverification_dateverified</name>
   <tag></tag>
   <elementGuidId>936c5b70-f52f-4f66-b0dc-96b5025de48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#verdate1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#verdate1</value>
   </webElementProperties>
</WebElementEntity>
