<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_cprbls_dateverified</name>
   <tag></tag>
   <elementGuidId>a809b6e4-7c5c-4a9f-a5fe-e05c4e27897d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#verdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#verdate2</value>
   </webElementProperties>
</WebElementEntity>
