<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_profcert_effectivedate</name>
   <tag></tag>
   <elementGuidId>484f0f9b-788e-4c9b-b9ef-8eb818f40a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdateu0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdateu0</value>
   </webElementProperties>
</WebElementEntity>
