<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_annaualpereval_effectivedate</name>
   <tag></tag>
   <elementGuidId>f721aabf-22bf-446d-8c89-b219ff375824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#efdateu8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#efdateu8</value>
   </webElementProperties>
</WebElementEntity>
