<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_profcert_dateverified</name>
   <tag></tag>
   <elementGuidId>543c495a-647c-4afd-8708-22a17b8f4f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#verdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#verdate0</value>
   </webElementProperties>
</WebElementEntity>
