<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cred_driverlicense_expirationdate</name>
   <tag></tag>
   <elementGuidId>de37422c-eeed-413f-8b6d-cdfcf9e5e62f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#exdate3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#exdate3</value>
   </webElementProperties>
</WebElementEntity>
