<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nrs_zipcode</name>
   <tag></tag>
   <elementGuidId>07710a0d-fc90-4b59-b970-5ff3cafc691f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#zipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#zipCode</value>
   </webElementProperties>
</WebElementEntity>
