<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>casecon_datecreated</name>
   <tag></tag>
   <elementGuidId>73113746-776a-47fa-aa9d-3da6ce84970c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#order_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#order_date</value>
   </webElementProperties>
</WebElementEntity>
