<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chart_menu</name>
   <tag></tag>
   <elementGuidId>03ad4489-2c5a-4b24-a63f-422158c6ad18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#togglesidelist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#togglesidelist</value>
   </webElementProperties>
</WebElementEntity>
