<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chart_tab</name>
   <tag></tag>
   <elementGuidId>11d9e777-ec32-467c-827b-2b9cac6fa15b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#togglesidelist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#togglesidelist</value>
   </webElementProperties>
</WebElementEntity>
