<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hospital_facility_admitdate</name>
   <tag></tag>
   <elementGuidId>4b1bf89b-2376-4b1d-8d0b-a5a711f9d8a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#admit_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#admit_date</value>
   </webElementProperties>
</WebElementEntity>
