<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hospital_dischargedate</name>
   <tag></tag>
   <elementGuidId>97005e8a-4f4d-43ae-809d-a1fdbbe4f015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#discharge_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#discharge_date</value>
   </webElementProperties>
</WebElementEntity>
