<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>referral_type_tf</name>
   <tag></tag>
   <elementGuidId>0e1b8fdc-05de-45a1-afbc-7ed21e9d62fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#referral_type_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#referral_type_chosen</value>
   </webElementProperties>
</WebElementEntity>
