<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>referral_phone</name>
   <tag></tag>
   <elementGuidId>c8857156-f221-468c-a114-af4582b7e581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#referral_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#referral_phone</value>
   </webElementProperties>
</WebElementEntity>
