<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_emth_endson</name>
   <tag></tag>
   <elementGuidId>00732fcc-9f2c-449c-8d7a-57f1b6650bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#tthendson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#tthendson</value>
   </webElementProperties>
</WebElementEntity>
