<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_emth_startson</name>
   <tag></tag>
   <elementGuidId>ebc2d2b1-2da8-4f58-b775-637b7dc889ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#tthstartson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#tthstartson</value>
   </webElementProperties>
</WebElementEntity>
