<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cc_interventions_textarea</name>
   <tag></tag>
   <elementGuidId>e30b4b46-335d-432f-a74a-cdafdb562e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#DMEREQ0040</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#DMEREQ0040</value>
   </webElementProperties>
</WebElementEntity>
