<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elim_indwelling_uc_datelc</name>
   <tag></tag>
   <elementGuidId>2c9204fb-1866-44d9-9b1a-2cfd0cb6359e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sooelimination0156</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sooelimination0156</value>
   </webElementProperties>
</WebElementEntity>
