<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cva_dateinserted</name>
   <tag></tag>
   <elementGuidId>0712a239-c8b0-4223-9524-f4d54aca98b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#VAAIT0099</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#VAAIT0099</value>
   </webElementProperties>
</WebElementEntity>
