<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1740_4</name>
   <tag></tag>
   <elementGuidId>e491113a-488d-4efd-a954-6647eba0683b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1740_BD_PHYSICAL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1740_BD_PHYSICAL</value>
   </webElementProperties>
</WebElementEntity>
