<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1740_6</name>
   <tag></tag>
   <elementGuidId>b72f853f-4ae2-424f-b33c-3d3cbd066d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1740_BD_DELUSIONS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1740_BD_DELUSIONS</value>
   </webElementProperties>
</WebElementEntity>
