<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continue_planofcare_tf</name>
   <tag></tag>
   <elementGuidId>e641520d-a31b-4a68-9d3b-b23c59166ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#planForNextVisitText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#planForNextVisitText</value>
   </webElementProperties>
</WebElementEntity>
