<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nic_zipcode</name>
   <tag></tag>
   <elementGuidId>c256a36d-b981-46a8-94b4-0e7fb763c6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#zipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#zipCode</value>
   </webElementProperties>
</WebElementEntity>
