<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_phyexam_dateverified</name>
   <tag></tag>
   <elementGuidId>8fddecb7-75e7-4a46-8b24-4e84923913c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpdatev0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpdatev0</value>
   </webElementProperties>
</WebElementEntity>
