<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_phyexam_expirationdate</name>
   <tag></tag>
   <elementGuidId>1029730a-3d1c-457e-8db8-8fb1617ed1ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpexpdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpexpdate0</value>
   </webElementProperties>
</WebElementEntity>
