<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_chestxray_effectivedate</name>
   <tag></tag>
   <elementGuidId>67beee34-b541-4f30-b9b4-3a8b7d8be865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpefdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpefdate2</value>
   </webElementProperties>
</WebElementEntity>
