<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_chestxray_dateverified</name>
   <tag></tag>
   <elementGuidId>a1876dd1-2482-4fdb-a5df-103ed0dbce91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpdatev2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpdatev2</value>
   </webElementProperties>
</WebElementEntity>
