<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_phyexam_effectivedate</name>
   <tag></tag>
   <elementGuidId>240644ce-4c84-4310-b994-d33b7e9379aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpefdate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpefdate0</value>
   </webElementProperties>
</WebElementEntity>
