<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hcred_chestxray_expirationdate</name>
   <tag></tag>
   <elementGuidId>4685920b-a12e-42a2-bfb3-c7fda542bcdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#hpexpdate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#hpexpdate2</value>
   </webElementProperties>
</WebElementEntity>
