<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcsum_dcnotifdate_physician</name>
   <tag></tag>
   <elementGuidId>af799219-5102-4ce0-8411-63f034024a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physicianDischargeDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physicianDischargeDate</value>
   </webElementProperties>
</WebElementEntity>
