<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adls_ms_bedmob_independent</name>
   <tag></tag>
   <elementGuidId>512699aa-5e32-4748-af28-c1f5545adcfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[2]/td[2]/table/tbody/tr[3]/td/div[2]/div/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#adlForm > div > fieldset > table > tbody > tr:nth-child(2) > td.oasis__answer.p-b-0 > table > tbody > tr:nth-child(3) > td > div.m-b-5.cont-opt.m-lopt-135 > div > label.radio.radio-inline.m-r-10.ng-scope.ng-isolate-scope.checked > input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;adlForm&quot;]/div/fieldset/table/tbody/tr[2]/td[2]/table/tbody/tr[3]/td/div[2]/div/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
