<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_commnote</name>
   <tag></tag>
   <elementGuidId>12f91f6c-c413-4541-ba96-f4ed35aa9fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#communicationnotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#communicationnotes</value>
   </webElementProperties>
</WebElementEntity>
