<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_physicianorder</name>
   <tag></tag>
   <elementGuidId>2bfcbdb3-96d8-4f91-83cd-b48aa1bbe3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#physicianordernotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#physicianordernotes</value>
   </webElementProperties>
</WebElementEntity>
