<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_time</name>
   <tag></tag>
   <elementGuidId>40abacbe-35d1-491b-9d72-deee0cf96a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderTime</value>
   </webElementProperties>
</WebElementEntity>
