<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bloodglucosetesting_other</name>
   <tag></tag>
   <elementGuidId>6ab15024-d8e8-40c1-aa4d-08f7146812d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ENDO0006</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ENDO0006</value>
   </webElementProperties>
</WebElementEntity>
