<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datelasttestingdone_tf</name>
   <tag></tag>
   <elementGuidId>b65918a5-1ec3-49cc-8b6e-c9920f7b4a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ENDO0018</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ENDO0018</value>
   </webElementProperties>
</WebElementEntity>
