<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glucometer_l3_tf</name>
   <tag></tag>
   <elementGuidId>12308aa5-fb27-40cd-b948-945dc6acdb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ENDO0013</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ENDO0013</value>
   </webElementProperties>
</WebElementEntity>
