<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glucometer_l1_tf</name>
   <tag></tag>
   <elementGuidId>1397255d-9c5a-4c0b-b895-dc1daf9aeed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ENDO0011</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ENDO0011</value>
   </webElementProperties>
</WebElementEntity>
