<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glucometer_l2_tf</name>
   <tag></tag>
   <elementGuidId>3b86b1c6-8dde-400a-9783-0791298a012e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#ENDO0012</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#ENDO0012</value>
   </webElementProperties>
</WebElementEntity>
