<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcsum_sentdate</name>
   <tag></tag>
   <elementGuidId>9015c4b9-825d-40a0-bb45-dfcf9b1efb3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#sentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#sentDate</value>
   </webElementProperties>
</WebElementEntity>
