<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dcsum_dischargedate</name>
   <tag></tag>
   <elementGuidId>69c9b83e-f2c0-4cf0-b29d-c2dce7932ada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#dischargeDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#dischargeDate</value>
   </webElementProperties>
</WebElementEntity>
