<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>do_orderdate</name>
   <tag></tag>
   <elementGuidId>8ddafc5a-e484-49a3-a441-e58c64b388b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderDate</value>
   </webElementProperties>
</WebElementEntity>
