<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>do_ordertime</name>
   <tag></tag>
   <elementGuidId>2c2b9415-b036-4515-af45-5c2da9e79d08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#orderTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#orderTime</value>
   </webElementProperties>
</WebElementEntity>
