<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>do_receiveddate</name>
   <tag></tag>
   <elementGuidId>b351006d-5b9d-4f28-9d89-6dc6f9aa73e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#receiveDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#receiveDate</value>
   </webElementProperties>
</WebElementEntity>
