<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_weekly_startson</name>
   <tag></tag>
   <elementGuidId>50b1c2c3-da37-43f0-85a3-3179697b75d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#weeklystartson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#weeklystartson</value>
   </webElementProperties>
</WebElementEntity>
