<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_weekly_endson</name>
   <tag></tag>
   <elementGuidId>ea627ff5-96cc-4777-ad1d-dfe61f43645b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#weeklyendson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#weeklyendson</value>
   </webElementProperties>
</WebElementEntity>
