<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hd_avshunt_ra</name>
   <tag></tag>
   <elementGuidId>9f232c9b-c582-4a63-8a83-169f36c69966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#HEMO0005</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#HEMO0005</value>
   </webElementProperties>
</WebElementEntity>
