<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hd_bruitpresent_yes</name>
   <tag></tag>
   <elementGuidId>a80ed9c8-298e-4c8c-b559-3b8f52cc1c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#HEMO0007</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#HEMO0007</value>
   </webElementProperties>
</WebElementEntity>
