<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hd_thrillstrong_yes</name>
   <tag></tag>
   <elementGuidId>54f7b3a6-2f98-440c-8ddd-6e07ee91cbe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#HEMO0009</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#HEMO0009</value>
   </webElementProperties>
</WebElementEntity>
