<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhoneNoExtension</name>
   <tag></tag>
   <elementGuidId>d943cbea-c088-457d-b072-a291fcb12eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/data/div[2]/div/form/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr/td/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/data/div[2]/div/form/fieldset/table/tbody/tr[15]/td[2]/table/tbody/tr/td/div/input</value>
   </webElementProperties>
</WebElementEntity>
