<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>State</name>
   <tag></tag>
   <elementGuidId>35d82923-3643-4a3b-9cf5-0e74d9e67944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#state_chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#state_chosen</value>
   </webElementProperties>
</WebElementEntity>
